/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/MatchResults': RouteRecordInfo<'/MatchResults', '/MatchResults', Record<never, never>, Record<never, never>>,
    '/MatchViewer': RouteRecordInfo<'/MatchViewer', '/MatchViewer', Record<never, never>, Record<never, never>>,
    '/MyMatches': RouteRecordInfo<'/MyMatches', '/MyMatches', Record<never, never>, Record<never, never>>,
  }
}
